/* Generated by the protocol buffer compiler.  DO NOT EDIT! */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C_NO_DEPRECATED
#define PROTOBUF_C_NO_DEPRECATED
#endif

#include "tcp_info.pb-c.h"
void   fss__tcp_info__init
                     (Fss__TcpInfo         *message)
{
  static Fss__TcpInfo init_value = FSS__TCP_INFO__INIT;
  *message = init_value;
}
size_t fss__tcp_info__get_packed_size
                     (const Fss__TcpInfo *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &fss__tcp_info__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t fss__tcp_info__pack
                     (const Fss__TcpInfo *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &fss__tcp_info__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t fss__tcp_info__pack_to_buffer
                     (const Fss__TcpInfo *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &fss__tcp_info__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Fss__TcpInfo *
       fss__tcp_info__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Fss__TcpInfo *)
     protobuf_c_message_unpack (&fss__tcp_info__descriptor,
                                allocator, len, data);
}
void   fss__tcp_info__free_unpacked
                     (Fss__TcpInfo *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &fss__tcp_info__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor fss__tcp_info__field_descriptors[34] =
{
  {
    "seconds",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Fss__TcpInfo, seconds),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "nanoseconds",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT64,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Fss__TcpInfo, nanoseconds),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "tcpi_state",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    PROTOBUF_C_OFFSETOF(Fss__TcpInfo, has_tcpi_state),
    PROTOBUF_C_OFFSETOF(Fss__TcpInfo, tcpi_state),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "tcpi_ca_state",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    PROTOBUF_C_OFFSETOF(Fss__TcpInfo, has_tcpi_ca_state),
    PROTOBUF_C_OFFSETOF(Fss__TcpInfo, tcpi_ca_state),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "tcpi_retransmits",
    5,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    PROTOBUF_C_OFFSETOF(Fss__TcpInfo, has_tcpi_retransmits),
    PROTOBUF_C_OFFSETOF(Fss__TcpInfo, tcpi_retransmits),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "tcpi_probes",
    6,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    PROTOBUF_C_OFFSETOF(Fss__TcpInfo, has_tcpi_probes),
    PROTOBUF_C_OFFSETOF(Fss__TcpInfo, tcpi_probes),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "tcpi_backoff",
    7,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    PROTOBUF_C_OFFSETOF(Fss__TcpInfo, has_tcpi_backoff),
    PROTOBUF_C_OFFSETOF(Fss__TcpInfo, tcpi_backoff),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "tcpi_options",
    8,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    PROTOBUF_C_OFFSETOF(Fss__TcpInfo, has_tcpi_options),
    PROTOBUF_C_OFFSETOF(Fss__TcpInfo, tcpi_options),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "tcpi_snd_wscale",
    9,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    PROTOBUF_C_OFFSETOF(Fss__TcpInfo, has_tcpi_snd_wscale),
    PROTOBUF_C_OFFSETOF(Fss__TcpInfo, tcpi_snd_wscale),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "tcpi_rcv_wscale",
    10,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    PROTOBUF_C_OFFSETOF(Fss__TcpInfo, has_tcpi_rcv_wscale),
    PROTOBUF_C_OFFSETOF(Fss__TcpInfo, tcpi_rcv_wscale),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "tcpi_rto",
    11,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    PROTOBUF_C_OFFSETOF(Fss__TcpInfo, has_tcpi_rto),
    PROTOBUF_C_OFFSETOF(Fss__TcpInfo, tcpi_rto),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "tcpi_ato",
    12,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    PROTOBUF_C_OFFSETOF(Fss__TcpInfo, has_tcpi_ato),
    PROTOBUF_C_OFFSETOF(Fss__TcpInfo, tcpi_ato),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "tcpi_snd_mss",
    13,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    PROTOBUF_C_OFFSETOF(Fss__TcpInfo, has_tcpi_snd_mss),
    PROTOBUF_C_OFFSETOF(Fss__TcpInfo, tcpi_snd_mss),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "tcpi_rcv_mss",
    14,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    PROTOBUF_C_OFFSETOF(Fss__TcpInfo, has_tcpi_rcv_mss),
    PROTOBUF_C_OFFSETOF(Fss__TcpInfo, tcpi_rcv_mss),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "tcpi_unacked",
    15,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    PROTOBUF_C_OFFSETOF(Fss__TcpInfo, has_tcpi_unacked),
    PROTOBUF_C_OFFSETOF(Fss__TcpInfo, tcpi_unacked),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "tcpi_sacked",
    16,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    PROTOBUF_C_OFFSETOF(Fss__TcpInfo, has_tcpi_sacked),
    PROTOBUF_C_OFFSETOF(Fss__TcpInfo, tcpi_sacked),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "tcpi_lost",
    17,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    PROTOBUF_C_OFFSETOF(Fss__TcpInfo, has_tcpi_lost),
    PROTOBUF_C_OFFSETOF(Fss__TcpInfo, tcpi_lost),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "tcpi_retrans",
    18,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    PROTOBUF_C_OFFSETOF(Fss__TcpInfo, has_tcpi_retrans),
    PROTOBUF_C_OFFSETOF(Fss__TcpInfo, tcpi_retrans),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "tcpi_fackets",
    19,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    PROTOBUF_C_OFFSETOF(Fss__TcpInfo, has_tcpi_fackets),
    PROTOBUF_C_OFFSETOF(Fss__TcpInfo, tcpi_fackets),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "tcpi_last_data_sent",
    20,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    PROTOBUF_C_OFFSETOF(Fss__TcpInfo, has_tcpi_last_data_sent),
    PROTOBUF_C_OFFSETOF(Fss__TcpInfo, tcpi_last_data_sent),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "tcpi_last_ack_sent",
    21,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    PROTOBUF_C_OFFSETOF(Fss__TcpInfo, has_tcpi_last_ack_sent),
    PROTOBUF_C_OFFSETOF(Fss__TcpInfo, tcpi_last_ack_sent),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "tcpi_last_data_recv",
    22,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    PROTOBUF_C_OFFSETOF(Fss__TcpInfo, has_tcpi_last_data_recv),
    PROTOBUF_C_OFFSETOF(Fss__TcpInfo, tcpi_last_data_recv),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "tcpi_last_ack_recv",
    23,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    PROTOBUF_C_OFFSETOF(Fss__TcpInfo, has_tcpi_last_ack_recv),
    PROTOBUF_C_OFFSETOF(Fss__TcpInfo, tcpi_last_ack_recv),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "tcpi_pmtu",
    24,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    PROTOBUF_C_OFFSETOF(Fss__TcpInfo, has_tcpi_pmtu),
    PROTOBUF_C_OFFSETOF(Fss__TcpInfo, tcpi_pmtu),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "tcpi_rcv_ssthresh",
    25,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    PROTOBUF_C_OFFSETOF(Fss__TcpInfo, has_tcpi_rcv_ssthresh),
    PROTOBUF_C_OFFSETOF(Fss__TcpInfo, tcpi_rcv_ssthresh),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "tcpi_rtt",
    26,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    PROTOBUF_C_OFFSETOF(Fss__TcpInfo, has_tcpi_rtt),
    PROTOBUF_C_OFFSETOF(Fss__TcpInfo, tcpi_rtt),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "tcpi_rttvar",
    27,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    PROTOBUF_C_OFFSETOF(Fss__TcpInfo, has_tcpi_rttvar),
    PROTOBUF_C_OFFSETOF(Fss__TcpInfo, tcpi_rttvar),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "tcpi_snd_ssthresh",
    28,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    PROTOBUF_C_OFFSETOF(Fss__TcpInfo, has_tcpi_snd_ssthresh),
    PROTOBUF_C_OFFSETOF(Fss__TcpInfo, tcpi_snd_ssthresh),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "tcpi_snd_cwnd",
    29,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    PROTOBUF_C_OFFSETOF(Fss__TcpInfo, has_tcpi_snd_cwnd),
    PROTOBUF_C_OFFSETOF(Fss__TcpInfo, tcpi_snd_cwnd),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "tcpi_advmss",
    30,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    PROTOBUF_C_OFFSETOF(Fss__TcpInfo, has_tcpi_advmss),
    PROTOBUF_C_OFFSETOF(Fss__TcpInfo, tcpi_advmss),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "tcpi_reordering",
    31,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    PROTOBUF_C_OFFSETOF(Fss__TcpInfo, has_tcpi_reordering),
    PROTOBUF_C_OFFSETOF(Fss__TcpInfo, tcpi_reordering),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "tcpi_rcv_rtt",
    32,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    PROTOBUF_C_OFFSETOF(Fss__TcpInfo, has_tcpi_rcv_rtt),
    PROTOBUF_C_OFFSETOF(Fss__TcpInfo, tcpi_rcv_rtt),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "tcpi_rcv_space",
    33,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    PROTOBUF_C_OFFSETOF(Fss__TcpInfo, has_tcpi_rcv_space),
    PROTOBUF_C_OFFSETOF(Fss__TcpInfo, tcpi_rcv_space),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "tcpi_total_retrans",
    34,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    PROTOBUF_C_OFFSETOF(Fss__TcpInfo, has_tcpi_total_retrans),
    PROTOBUF_C_OFFSETOF(Fss__TcpInfo, tcpi_total_retrans),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned fss__tcp_info__field_indices_by_name[] = {
  1,   /* field[1] = nanoseconds */
  0,   /* field[0] = seconds */
  29,   /* field[29] = tcpi_advmss */
  11,   /* field[11] = tcpi_ato */
  6,   /* field[6] = tcpi_backoff */
  3,   /* field[3] = tcpi_ca_state */
  18,   /* field[18] = tcpi_fackets */
  22,   /* field[22] = tcpi_last_ack_recv */
  20,   /* field[20] = tcpi_last_ack_sent */
  21,   /* field[21] = tcpi_last_data_recv */
  19,   /* field[19] = tcpi_last_data_sent */
  16,   /* field[16] = tcpi_lost */
  7,   /* field[7] = tcpi_options */
  23,   /* field[23] = tcpi_pmtu */
  5,   /* field[5] = tcpi_probes */
  13,   /* field[13] = tcpi_rcv_mss */
  31,   /* field[31] = tcpi_rcv_rtt */
  32,   /* field[32] = tcpi_rcv_space */
  24,   /* field[24] = tcpi_rcv_ssthresh */
  9,   /* field[9] = tcpi_rcv_wscale */
  30,   /* field[30] = tcpi_reordering */
  17,   /* field[17] = tcpi_retrans */
  4,   /* field[4] = tcpi_retransmits */
  10,   /* field[10] = tcpi_rto */
  25,   /* field[25] = tcpi_rtt */
  26,   /* field[26] = tcpi_rttvar */
  15,   /* field[15] = tcpi_sacked */
  28,   /* field[28] = tcpi_snd_cwnd */
  12,   /* field[12] = tcpi_snd_mss */
  27,   /* field[27] = tcpi_snd_ssthresh */
  8,   /* field[8] = tcpi_snd_wscale */
  2,   /* field[2] = tcpi_state */
  33,   /* field[33] = tcpi_total_retrans */
  14,   /* field[14] = tcpi_unacked */
};
static const ProtobufCIntRange fss__tcp_info__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 34 }
};
const ProtobufCMessageDescriptor fss__tcp_info__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "fss.tcp_info",
  "TcpInfo",
  "Fss__TcpInfo",
  "fss",
  sizeof(Fss__TcpInfo),
  34,
  fss__tcp_info__field_descriptors,
  fss__tcp_info__field_indices_by_name,
  1,  fss__tcp_info__number_ranges,
  (ProtobufCMessageInit) fss__tcp_info__init,
  NULL,NULL,NULL    /* reserved[123] */
};
